CTONET-780 - Test pod priviliges
test-network-function/test-network-function pull request #144
Opened 2021-04-05 07:13 UTC by ydayagi

We read pod's service account and use it to understand the roles it
binds to

https://issues.redhat.com/browse/CTONET-780

2021-04-05 19:06 UTC, ryandgoulding commented
Please fix the lint errors exposed by running `make lint`.

2021-04-05 19:06 UTC, ryandgoulding requested changes

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/clusterrolebinding/clusterrolebinding_test.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/clusterrolebinding/doc.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/rolebinding/doc.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/rolebinding/rolebinding.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/rolebinding/rolebinding_test.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/serviceaccount/doc.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/serviceaccount/serviceaccount.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/handlers/serviceaccount/serviceaccount_test.go
> +// Copyright (C) 2020 Red Hat, Inc.
2021

2021-04-05 19:06 UTC, ryandgoulding commented on pkg/tnf/identifier/identifiers.go
> +}
Please add appropriate entries to the Catalog map here:
https://github.com/test-network-function/test-network-function/blob/main/pkg/tnf/identifier/identifiers.go#L70

2021-04-05 19:07 UTC, ryandgoulding commented
Looks great in general.  I have a few small suggestions inlined aside from the `lint` issue above.  Great work!

2021-04-06 11:49 UTC, ryandgoulding approved these changes

2021-04-06 13:45 UTC, crwr45 approved these changes

2021-04-06 13:45 UTC, merged