Test that node kernels are not tainted
test-network-function/test-network-function pull request #157
Opened 2021-04-12 06:59 UTC by ydayagi

https://issues.redhat.com/browse/CTONET-844

2021-04-12 12:31 UTC, ryandgoulding requested changes

2021-04-12 12:31 UTC, ryandgoulding commented on pkg/tnf/identifier/identifiers.go
> +			dependencies.OcBinaryName,
Also requires `echo`.

2021-04-13 12:29 UTC, ryandgoulding commented
The only reservation I have about merging this involves the fact that doing so with this in the `generic` test suite will cause minikube `local-test-infra` to fail.  This is due to the fact that opening a debug pod for the `minikube` node does not work.  We will need some sort of flag, environment variable, etc. to further restrict the tests aside from `ginkgo.focus` so that we can skip this locally.  Need a few minutes to think about the best way to handle this going forward.

2021-04-18 09:05 UTC, ydayagi commented
@ryandgoulding what can be done to make this PR pass?

2021-04-19 11:40 UTC, ryandgoulding commented
@ydayagi can you make this test optional using based one whether the `TNF_MINIKUBE_ONLY` is set to `true` or `false`?  Aside from that, please just resolve the conflicts.

2021-04-19 18:21 UTC, ryandgoulding approved these changes

2021-04-19 18:21 UTC, merged