ensure a CNF is usable after cordoning a node
test-network-function/test-network-function pull request #173
Opened 2021-04-28 20:35 UTC by ydayagi

Read the CNF namespace's deployments
Drain at least one node that is executing deployment pods

https://issues.redhat.com/browse/CTONET-877

2021-04-28 20:37 UTC, ydayagi commented
@ryandgoulding I created this draft PR so we can review the code and idea before end of impl

2021-05-03 21:19 UTC, ryandgoulding requested changes

2021-05-03 21:19 UTC, ryandgoulding commented on pkg/tnf/handlers/deploymentsdrain/deploymentsdrain.go
> +	drainTimeout := timeout * drainTimeoutPercentage / 100
Just in case others are reviewing and wondering;  it would appear that time.Duration is smart enough to handle `float-like` numbers and possible type-upgrades even when multiplying by `int` types.  This is the type of Go operator overloading behavior I am not super familiar with, and had to punch it into the playground to confirm:

https://play.golang.org/p/2bMweG0-5jZ

2021-05-03 21:19 UTC, ryandgoulding commented on pkg/tnf/handlers/deploymentsnodes/deploymentsnodes.go
> +	dnRegex      = "(?s).+"
Same as above;  can we use something similar to:
```
(?m)(NAME\s+)(NODE)(.*)
```
This would avoid matching the empty string, and hopefully any race conditions as well.

2021-05-03 21:23 UTC, ydayagi commented on pkg/tnf/handlers/deployments/deployments.go
> +	dpRegex = "(?s).+"
This regex is already in use in previous handlers.
It does not allow empty output.
It expects at least one character.
This is how I distinguish error from successful execution.
By successful I mean that the executable was executed and produced some kind of output.

2021-05-03 21:26 UTC, ydayagi commented on pkg/tnf/handlers/deploymentsdrain/deploymentsdrain.go
> +	drainTimeout := timeout * drainTimeoutPercentage / 100
I am not sure what you're trying to focus on here.
If you are referring to the Duration type's ability to hold float then the answer is yes.
I read docs and tested.

2021-05-03 21:27 UTC, ydayagi commented on pkg/tnf/handlers/deploymentsnodes/deploymentsnodes.go
> +	dnRegex      = "(?s).+"
see previous comments.

2021-05-03 21:55 UTC, ryandgoulding commented on pkg/tnf/handlers/deployments/deployments.go
> +	dpRegex = "(?s).+"
Oh okay, I misread the `+` as a `*`.  You are right, this is fine.

2021-05-03 21:55 UTC, ryandgoulding commented on pkg/tnf/handlers/deploymentsdrain/deploymentsdrain.go
> +	drainTimeout := timeout * drainTimeoutPercentage / 100
Yes, just leaving it in case Charlie or anyone else reviewing was curious.  No action is needed.

2021-05-03 21:56 UTC, ryandgoulding approved these changes

2021-05-03 21:56 UTC, merged