CTONET-971 + CTONET-974
test-network-function/test-network-function pull request #214
Opened 2021-05-25 12:42 UTC by isaacdorfman

Added nodeSelector/nodeAffinity and testGracePeriod to the documentation

2021-05-25 18:10 UTC, crwr45 commented
Please rebase and resolve conflicts

2021-06-02 19:56 UTC, ryandgoulding requested changes

2021-06-02 19:56 UTC, ryandgoulding commented on README.md
> +4) Print a warning if a pod's terminationGracePeriod is set to 30s(the default in Kubernetes)
Please replace `Kubernetes` with `OpenShift`.

2021-06-02 19:57 UTC, ryandgoulding commented on README.md
> +3) Print a warning if a pod spec specifies nodeSelector/nodeAffinity
Please end the sentence with a period.

2021-06-07 13:06 UTC, isaacdorfman commented
@ryandgoulding @crwr45 Fixed and rebased

2021-06-07 15:07 UTC, crwr45 approved these changes

2021-06-07 15:30 UTC, merged