stop testing containers for pod tests
test-network-function/test-network-function pull request #267
Opened 2021-07-05 07:12 UTC by ydayagi

https://issues.redhat.com/browse/CNFCERT-40
Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>

2021-07-05 15:47 UTC, jun-rh commented on test-network-function/generic/suite.go
> +		if _, ok := podsToExcludeFromConnectivityTests[podKey]; !ok {
You mean all the containers in a pod share the same network interface?

2021-07-05 16:06 UTC, HamadiSE commented on test-network-function/generic/suite.go
> +		if _, ok := podsToExcludeFromConnectivityTests[podKey]; !ok {
my bad, right/ containers are within a pod. and its the POD who has the IP. my comment is not valid.

2021-07-05 18:07 UTC, jun-rh commented
@ryandgoulding @crwr45 I am surprised to see this many pod level tests in generic. Does it makes more sense to move them to the "container" spec where other pod level tests are and rename the spec to something else?

2021-07-06 13:09 UTC, HamadiSE approved these changes

2021-07-07 13:40 UTC, ryandgoulding commented
> @ryandgoulding @crwr45 I am surprised to see this many pod level tests in generic. Does it makes more sense to move them to the "container" spec where other pod level tests are and rename the spec to something else?

Dealer's choice.  Historically, the `container` spec was abstracted by a contributor to isolate it from existing test cases during development.  One could argue that some tests belong there, or to get rid of `container` altogether and combine it with `generic`.

2021-07-07 15:34 UTC, crwr45 requested changes
This looks like a step in the right direction. I'm lacking some of the context to know what followup changes are coming but assuming a more complete refactoring and restructuring around containers/pods, the code is good.

This does need an update to the documentation to ensure the new behaviour is clear.

2021-07-07 16:06 UTC, jun-rh commented
Thanks @ryandgoulding @crwr45
We plan to step back and look at test categorization overall. Once we have a good strategy on that, we will design the config part accordingly (pod list vs container list, common or per suite etc).

2021-07-15 07:12 UTC, pkliczewski commented
@ydayagi do we still want to finalize this PR?

2021-07-22 13:57 UTC, closed without merging