CNFCERT-73
test-network-function/test-network-function pull request #297
Opened 2021-08-09 15:15 UTC by isaacdorfman

Added sysctlAllConfigsArgs identifier.

2021-08-09 15:30 UTC, jun-rh requested changes
You updated the handler catalog, not the test case catalog. See the other identifiers.go under test-netowrk-function.

2021-08-09 15:30 UTC, jun-rh commented on pkg/tnf/dependencies/binaries.go
> +	SysctlBinaryName = "oc"
Is this intentional or it should be a different command name?

2021-08-12 06:59 UTC, pkliczewski commented
@isaacdorfman please rebase

2021-08-12 13:45 UTC, jun-rh approved these changes

2021-08-12 16:56 UTC, HamadiSE approved these changes

2021-08-12 16:57 UTC, merged