Add_test_identifier_for_isRedhatRelease
test-network-function/test-network-function pull request #308
Opened 2021-08-17 18:14 UTC by shimritproj

2021-08-17 18:34 UTC, HamadiSE commented
@shimritproj can you please solve the conflicts ?

2021-08-17 23:46 UTC, HamadiSE commented on test-network-function/identifiers/identifiers.go
> +		Description: formDescription(TestIsRedHatReleaseIdentifier,
this description does not match the test. Needs to be updated.

2021-08-17 23:48 UTC, HamadiSE requested changes

2021-08-17 23:48 UTC, HamadiSE commented on test-network-function/identifiers/identifiers.go
> +		Description: formDescription(TestIsRedHatReleaseIdentifier,
this text is meant for the end user to figure out what's wrong with the test case and some hints on how to fix it.

2021-08-18 15:38 UTC, jun-rh commented on test-network-function/platform/suite.go
> +		testContainerIsRedHatRelease(configData.TestOrchestrator)
Remove this line. No need to test our own container.

2021-08-19 13:29 UTC, HamadiSE requested changes

2021-08-19 13:29 UTC, HamadiSE commented on test-network-function/identifiers/identifiers.go
> +		Remediation: `You should recreate the nodes, recreating is recommended because there might be other unknown changes`,
my comments were explanation and example, please update the description to indicate what the test is doing actually.

2021-08-23 16:14 UTC, HamadiSE commented on test-network-function/platform/suite.go
> +		testIsRedHatRelease(env)
this should be inside if block.
it should in line 80.

2021-08-23 16:22 UTC, HamadiSE approved these changes

2021-08-23 17:40 UTC, wying3 approved these changes

2021-08-23 17:41 UTC, merged