Change the default network mode to host in run-tnf-container.sh
test-network-function/test-network-function pull request #331
Opened 2021-08-31 08:49 UTC by aabughosh

2021-08-31 17:07 UTC, jun-rh commented on README.md
> +* `-n` gives the network mode of the container. Defaults set to `host`, if the node is in selinux enable then need to set the value to somthing that are not host. See the [docker run --network parame
... 'host', which requires selinux to be disabled. Alternatively, 'bridge' mode can be used with selinux if TNF_CONTAINER_CLIENT is set to "docker" or running the test as root.

2021-08-31 17:08 UTC, jun-rh requested changes
Inline

2021-08-31 21:37 UTC, wying3 submitted a review, later dismissed

2021-08-31 23:02 UTC, wying3 requested changes
the line 182 in  run-tnf-container.sh  need to be changed to $CONTAINER_NETWORK_MODE, otherwise print out will be wrong
this is old bug.

2021-09-01 08:10 UTC, aabughosh commented on run-tnf-container.sh
> +          echo "-n CONTAINER_NETWORK_MODE"
done

2021-09-01 13:24 UTC, jun-rh approved these changes

2021-09-01 13:59 UTC, HamadiSE approved these changes

2021-09-01 14:29 UTC, merged